services:
  mongo-auth:
    image: mongo:7
    networks: [yazlab-internal]

  mongo-user:
    image: mongo:7
    networks: [yazlab-internal]

  mongo-message:
    image: mongo:7
    networks: [yazlab-internal]

  mongo-dispatcher:
    image: mongo:7
    networks: [yazlab-internal]

  auth-service:
    build: ./auth-service
    networks: [yazlab-internal]
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-auth:27017/auth_db
    expose:
      - "8081"
    depends_on: [mongo-auth]

  user-service:
    build: ./user-service
    networks: [yazlab-internal]
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-user:27017/user_db
    expose:
      - "8082"
    depends_on: [mongo-user]

  message-service:
    build: ./message-service
    networks: [yazlab-internal]
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-message:27017/message_db
    expose:
      - "8083"
    depends_on: [mongo-message]

  dispatcher:
    build: ./dispatcher
    ports:
      - "8080:8080"
    networks: [yazlab-internal]
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-dispatcher:27017/yazlab_dispatcher
      YAZLAB_SERVICES_AUTH: http://auth-service:8081
      YAZLAB_SERVICES_USER: http://user-service:8082
      YAZLAB_SERVICES_MESSAGE: http://message-service:8083
    depends_on:
      - mongo-dispatcher
      - auth-service
      - user-service
      - message-service

networks:
  yazlab-internal:
    driver: bridge
