spring.application.name=dispatcher
spring.data.mongodb.uri=mongodb://localhost:27017/yazlab_dispatcher
# POST govdesini (JSON) bozmayi onlemek icin form-url-encoded parser kapali
spring.mvc.formcontentfilter.enabled=false

yazlab.services.user=http://localhost:8082
yazlab.services.message=http://localhost:8083
yazlab.services.auth=http://localhost:8081
